interval = "5s"

[power_strip]
hostname = "kasa"

[[sensors]]
name = "ground-warm"
kind = "w1-therm"
read_from = "/tmp/w1-therm-warm"
target = 26.7
range = 1.25
plug_idx = 0

[[sensors]]
name = "ground-cool"
kind = "w1-therm"
read_from = "/tmp/w1-therm-cool"
target = 25.2
range = 1.25
plug_idx = 1
