interval = "5s"

[[devices]]
name = "plug"
kind = "kasa"
connection = "kasa"

[[sensors]]
name = "ground-warm"
kind = "w1-therm"
read_from = "/tmp/w1-therm-warm"
target = 26.7
range = 1.25
device = "plug"
subdevice = "0"

[[sensors]]
name = "ground-cool"
kind = "w1-therm"
read_from = "/tmp/w1-therm-cool"
target = 25.2
range = 1.25
device = "plug"
subdevice = "1"
